//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raseedapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_detail_Table
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone_no { get; set; }
        public byte[] remarks { get; set; }
        public int job_id { get; set; }
    
        public virtual jobsheetTable jobsheetTable { get; set; }
    }
}
