//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raseedapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobsheetTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jobsheetTable()
        {
            this.Customer_detail_Table = new HashSet<Customer_detail_Table>();
            this.Product_detail_Table = new HashSet<Product_detail_Table>();
            this.Product_detail_Table1 = new HashSet<Product_detail_Table>();
            this.reparing_detail_Table = new HashSet<reparing_detail_Table>();
        }
    
        public int Id { get; set; }
        public string cash_memo_no { get; set; }
        public Nullable<System.DateTime> recived_date { get; set; }
        public Nullable<System.DateTime> promise_date { get; set; }
        public Nullable<System.DateTime> ready_on { get; set; }
        public Nullable<System.DateTime> dliverd_on { get; set; }
        public Nullable<System.DateTime> remarks { get; set; }
        public int user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_detail_Table> Customer_detail_Table { get; set; }
        public virtual userTable userTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_detail_Table> Product_detail_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_detail_Table> Product_detail_Table1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reparing_detail_Table> reparing_detail_Table { get; set; }
    }
}
