//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raseedapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_detail_Table
    {
        public int Id { get; set; }
        public string brand_name { get; set; }
        public string artical_type { get; set; }
        public string accessoris { get; set; }
        public string serial_no { get; set; }
        public Nullable<System.DateTime> date_of_purchase { get; set; }
        public string wrranty_card_no { get; set; }
        public Nullable<int> previous_job_id { get; set; }
        public int job_id { get; set; }
    
        public virtual jobsheetTable jobsheetTable { get; set; }
        public virtual jobsheetTable jobsheetTable1 { get; set; }
    }
}
