//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raseedapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reparing_detail_Table
    {
        public int Id { get; set; }
        public Nullable<int> eng_no { get; set; }
        public string product_code { get; set; }
        public string description { get; set; }
        public Nullable<int> quntitay { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> job_id { get; set; }
    
        public virtual jobsheetTable jobsheetTable { get; set; }
    }
}
